Repository Knock-and-knock/frontend, pull requests merged in 2024-09, with the labels that each got.

#94 🌟(#6) 회원가입 input관련 수정사항 반영
  src/consume/Consumption.js
  src/consume/component/ConsumDetailModal.css
  src/consume/component/ConsumDetailModal.js
  src/consume/component/ConsumList.js
  src/home/component/CardBottom.css
  src/home/component/CardBottom.js
  src/home/component/CardSlide.css
  src/login/LoginPw.js
  src/login/component/modal/LoginOptionModal.js
  src/signUp/component/Register.js
Labels: 🛠️fix

#95 🌟(#) 복지 수정중
  .gradle/8.8/fileHashes/fileHashes.lock
  src/App2.js
  src/consumeReport/ConsumeReport.css
  src/consumeReport/component/ConsumeReportInfo.js
  src/header/BlueHeader.js
  src/header/Header.js
  src/header/Header.module.css
  src/welfare/component/WelfareAddressModal.js
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfareInputAddress.js
  src/welfare/component/WelfareInputHeight.js
  src/welfare/component/WelfareReserveCancelModal.js
  src/welfare/component/WelfareReservedItem.js
  src/welfare/component/WelfareReservedList.js
  src/welfare/css/WelfareReservedList.module.css
Labels: 🐞bugfix

#98 보호자의 일반사용자 대신 예약 및 예약 확인 기능 구현 완료
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfareHanwoolModal.js
  src/welfare/component/WelfareHouseworkModal.js
  src/welfare/component/WelfareInputHeight.js
  src/welfare/component/WelfareMain.js
  src/welfare/component/WelfareNursingModal.js
  src/welfare/component/WelfareReservedItem.js
  src/welfare/component/WelfareReservedList.js
  src/welfare/css/WelfareReservedList.module.css
Labels: 🌟feature

#99 🌟(#38) 카드내역 상세 조회 연결
  src/alarm/AlarmList.js
  src/alarm/component/AlarmDetailModal.js
  src/alarm/component/AlarmHistory.js
  src/alarm/component/AlarmMark.css
  src/alarm/component/AlarmMark.js
  src/consume/component/ConsumDetailModal.css
  src/consume/component/ConsumDetailModal.js
  src/consume/component/ConsumList.css
  src/consume/component/ConsumList.js
  src/login/LoginPw.js
  src/signUp/component/PinCheck.js
  src/signUp/component/PinSetup.js
  src/signUp/component/VerifyCode.js
Labels: 🛠️fix, 🌟feature

#100 🌟(#65 ) ssl 설정 추가
  .github/workflows/deploy.yml
  .gitignore
  nginx/nginx.conf
Labels: 🌏deploy

#102 🌟(#102) 가족카드 수정
  src/cardCreate/CardCreate.css
  src/cardCreate/application/CardApp.js
  src/cardCreate/application/FamilyDefaultInfo.js
  src/cardCreate/application/FamilyExtraInfo.js
  src/matching/Match.css
  src/matching/button/button.css
Labels: 🔄️refactoring

#103 🌟(#103) 가족카드발급수정
  src/cardCreate/application/CardApp.js
Labels: 🔄️refactoring

#104 🌟(#103) 가족카드발급 코드수정
  src/cardCreate/application/CardApp.js
  src/cardCreate/application/FamilyDefaultInfo.js
Labels: 🔄️refactoring

#106 🌟(#65 ) deploy.yml 수정
  .github/workflows/deploy.yml
Labels: 🌏deploy

#107 🌟(#103 ) 가족카드수정
  src/cardCreate/application/CardApp.js
Labels: 🔄️refactoring

#109 🌟(#104 ) greeting기능 제거
  src/chat/VoiceChat.js
Labels: 🔄️refactoring

#110 복지 결제 내역 소비내역에도 추가하기
  src/App2.js
  src/welfare/component/WelfareCheckPW.js
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfarePayCompl.js
  src/welfare/component/WelfareReservedList.js
Labels: 🌟feature

#111 🌟(#6) 회원가입 input 넓이 조정
  src/home/component/CardSection.js
  src/image/hanwool2.png
  src/image/hanwool_2.png
  src/image/housework2.png
  src/image/housework_2.png
  src/image/housework_3.png
  src/image/nursing2.png
  src/image/nursing_2.png
  src/image/nursing_3.png
  src/onboarding/OnboardingPage.js
  src/signUp/SignUpMain.css
  src/signUp/SignUpMain.js
  src/signUp/component/PinCheck.js
  src/signUp/component/QuickLoginSetup.js
  src/signUp/component/Register.js
  src/signUp/component/VerifyCode.js
  src/signUp/component/header/SignUpHeader.css
  src/welfare/component/DolbomMain.js
  src/welfare/component/WelfareList.js
  src/welfare/css/WelfareList.module.css
Labels: 🎨design

#116 🌟(#114) 복지서비스 예약 오류 수정
  src/welfare/component/WelfareHanwoolModal.js
  src/welfare/component/WelfareHouseworkModal.js
  src/welfare/component/WelfareNursingModal.js
  src/welfare/component/WelfarePayCompl.js
  src/welfare/component/WelfareReservedItem.js
  src/welfare/component/WelfareReservedList.js
Labels: 🌟feature, 🐞bugfix

#118 [Bugfix]: 너무 다양한 버그 수정
  src/App2.js
  src/header/Header.module.css
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfareHanwoolModal.js
  src/welfare/component/WelfareHouseworkModal.js
  src/welfare/component/WelfareInputAddress.js
  src/welfare/component/WelfareList.js
  src/welfare/component/WelfareMain.js
  src/welfare/component/WelfareNursingModal.js
  src/welfare/component/WelfareReservedItem.js
  src/welfare/css/WelfareInputAddress.module.css
  src/welfare/css/WelfareInputBirth.module.css
  src/welfare/css/WelfareInputDisease.module.css
  src/welfare/css/WelfareInputHeight.module.css
  src/welfare/css/WelfarePayCompl.module.css
  src/welfare/css/WelfareReserveModal.module.css
Labels: 🐞bugfix

#119 🌟(#114) 발표 위한 복지서비스 수정
  src/App2.js
  src/welfare/component/WelfareCheckPW.js
  src/welfare/component/WelfareCheckSpec.js
Labels: 🛠️fix

#122 merge to main
  .github/workflows/deploy.yml
Labels: 🌏deploy

#121 🌟(#101 )대문자입력수정
  src/cardCreate/application/FamilyDefaultInfo.js
  src/cardCreate/application/FamilyExtraInfo.js
  src/chat/VoiceChatMovePageModal.js
  src/matching/MatchingModal.css
  src/matching/MatchingModal.js
  src/welfare/component/DolbomMain.js
Labels: 🔄️refactoring

#123 🌟(#78 ) 생체인식 지문 및 안면인식으로 제한
  src/login/LoginBio.js
  src/signUp/component/QuickLoginSetup.js
Labels: 🌟feature

#124 🌟(#126 ) 카드발급유무 복지예약 판단
  src/welfare/component/DolbomMain.js
Labels: 🌟feature

#127 🌟(#125 ) 복지 예약 시 정보 불러오기 구현 중
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  src/welfare/component/DolbomMain.js
  src/welfare/component/WelfareNursingModal.js
Labels: 🌟feature

#129 🌟(#128) 복지서비스 결제 카드 페이지 구현
  src/App2.js
  src/consume/component/ConsumCard.js
  src/home/MainPage.js
  src/welfare/component/WelfareCheckPW.js
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfareList.js
  src/welfare/component/WelfarePay.js
  src/welfare/css/WelfareList.module.css
  src/welfare/css/WelfarePay.css
Labels: 🌟feature

#131 🌟(#130 ) 가족카드, 개인카드 이미지 추가
  src/cardCreate/CardCreate.css
  src/cardCreate/CardCreate.js
  src/image/familyCard.png
  src/image/personalCard.png
Labels: 🔄️refactoring

#134 🌟(#133 ) 비 로그인 시 로그인 화면으로
  src/App1.js
  src/App2.js
  src/App3.js
  src/PrivateRoute.js
Labels: 🌟feature

#135 🌟(#125 ) 복지 예약 정보 입력 구현중
  src/welfare/component/DolbomMain.js
  src/welfare/component/WelfareNursingModal.js
  src/welfare/css/DolbomMain.module.css
  src/welfare/css/WelfareCheckPW.module.css
  src/welfare/css/WelfareCheckSpec.module.css
  src/welfare/css/WelfareInputBirth.module.css
  src/welfare/css/WelfareInputDisease.module.css
  src/welfare/css/WelfareInputGender.module.css
  src/welfare/css/WelfareInputHeight.module.css
Labels: 🌟feature

#132 🌟(#65 ) Dockerfile 환경변수 추가
  Dockerfile
Labels: 🔄️refactoring

#136 merge to main
  .github/workflows/deploy.yml
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  Dockerfile
  src/App1.js
  src/App2.js
  src/App3.js
  src/PrivateRoute.js
  src/cardCreate/CardCreate.css
  src/cardCreate/CardCreate.js
  src/cardCreate/application/FamilyDefaultInfo.js
  src/cardCreate/application/FamilyExtraInfo.js
  src/chat/VoiceChatMovePageModal.js
  src/consume/component/ConsumCard.js
  src/home/MainPage.js
  src/image/familyCard.png
  src/image/personalCard.png
  src/login/LoginBio.js
  src/matching/MatchingModal.css
  src/matching/MatchingModal.js
  src/signUp/component/QuickLoginSetup.js
  src/welfare/component/DolbomMain.js
  src/welfare/component/WelfareCheckPW.js
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfareList.js
  src/welfare/component/WelfareNursingModal.js
  src/welfare/component/WelfarePay.js
  src/welfare/css/DolbomMain.module.css
  src/welfare/css/WelfareCheckPW.module.css
  src/welfare/css/WelfareCheckSpec.module.css
  src/welfare/css/WelfareInputBirth.module.css
  src/welfare/css/WelfareInputDisease.module.css
  src/welfare/css/WelfareInputGender.module.css
  src/welfare/css/WelfareInputHeight.module.css
  src/welfare/css/WelfareList.module.css
  src/welfare/css/WelfarePay.css
Labels: 🌏deploy

#137 🌟(#133 ) 회원가입은 뺴고
  src/App3.js
Labels: 🔄️refactoring

#138 🌟(#65 ) Dockerfile 환경변수 수정
  Dockerfile
Labels: 🌏deploy

#141 🌟(#134 ) 디자인 추가수정
  src/cardCreate/CardCreate.css
  src/cardCreate/CardCreate.js
  src/cardCreate/application/CardApplication.css
  src/chat/VoiceChat.js
  src/matching/MatchingModal.css
Labels: 🎨design

#140 🌟(#125 ) 부가 정보 복지 예약 시 정보 넘기기 구현 중
  src/welfare/component/DolbomMain.js
  src/welfare/component/WelfareHanwoolModal.js
  src/welfare/component/WelfareHouseworkModal.js
  src/welfare/component/WelfareNursingModal.js
Labels: 🌟feature

#142 🌟(#128) 간편결제 비밀번호 구현
  src/App2.js
  src/consume/component/ConsumCard.css
  src/consume/component/ConsumCard.js
  src/home/component/CardSection.css
  src/home/component/CardSection.js
  src/home/component/WelfareSlide.css
  src/image/familyCard2.png
  src/image/personalCard2.png
  src/login/service/ApiService.js
  src/welfare/component/WelfareCheckPW.js
  src/welfare/component/WelfarePay.js
  src/welfare/component/WelfareSetPW.js
  src/welfare/css/WelfarePay.css
Labels: 🌟feature

#143 🌟(#65 ) Dockerfile 수정
  Dockerfile
Labels: 🌏deploy

#145 🌟(#65 ) Dockerfile .env 복사코드 삭제
  Dockerfile
Labels: 🌏deploy

#147 🌟(#65 ) Dockerfile 수정
  Dockerfile
Labels: 🌏deploy

#149 🌟(#128) url 변경
  .gitignore
  src/login/service/ApiService.js
  src/welfare/component/WelfareCheckPW.js
Labels: 🐞bugfix

#151 🌟(#150 ) 매칭모달 매칭 이름 불러오기
  src/cardCreate/application/ExtraInfo.js
  src/home/MainPage.js
  src/matching/MatchingModal.js
Labels: 🌟feature

#153 🌟(#65 ) Dockerfile 수정
  Dockerfile
Labels: 🌏deploy

#155 🌟(#125 ) 복지 정보 넘기기 구현 완료
  src/header/Header.module.css
  src/login/LoginBio.js
  src/login/service/ApiService.js
  src/welfare/component/DolbomMain.js
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfareList.js
  src/welfare/component/WelfareNursingModal.js
  src/welfare/css/WelfareCheckPW.module.css
  src/welfare/css/WelfareCheckSpec.module.css
  src/welfare/css/WelfareInputBirth.module.css
  src/welfare/css/WelfareInputDisease.module.css
  src/welfare/css/WelfareInputGender.module.css
  src/welfare/css/WelfareInputHeight.module.css
  src/welfare/css/WelfareSetPW.module.css
Labels: 🌟feature

#156 🌟(#128 ) 버튼 css 수정
  src/alarm/component/AlarmHistory.js
  src/cardCreate/application/FamilyDefaultInfo.js
  src/consume/Consumption.css
  src/consume/Consumption.js
  src/consume/component/ConsumDateModal.css
  src/consume/component/ConsumDateModal.js
  src/consume/component/ConsumDetailModal.js
  src/home/component/WelfareSlide.js
  src/image/familyCard3.png
  src/image/personalCard3.png
  src/welfare/component/WelfareCheckPW.js
  src/welfare/component/WelfareList.js
  src/welfare/component/WelfarePay.js
  src/welfare/component/WelfareSetPW.js
  src/welfare/css/WelfareCheckPW.module.css
  src/welfare/css/WelfarePay.css
  src/welfare/css/WelfareSetPW.module.css
Labels: 🎨design

#158 🌟(#157)온보딩 화면 제작
  src/App1.js
  src/image/logo.png
  src/image/logo.svg
  src/image/onboarding-img.png
  src/onboarding/OnboardingNew.css
  src/onboarding/OnboardingNew.js
Labels: 🎨design

#159 🌟(#6) 간편로그인 버그 수정중
  src/alarm/AlarmList.js
  src/alarm/component/AlarmDetailModal.css
  src/alarm/component/AlarmDetailModal.js
  src/alarm/component/AlarmMark.js
  src/consume/Consumption.css
  src/consume/Consumption.js
  src/consume/component/ConsumDateModal.css
  src/consume/component/ConsumDateModal.js
  src/consume/component/ConsumFilter.css
  src/consume/component/ConsumList.css
  src/consume/component/ConsumList.js
  src/home/component/Button.js
  src/home/component/CardSlide.js
  src/mypage/MyPage.css
  src/mypage/MyPage.js
  src/mypage/component/InfoInput.js
  src/mypage/component/ModifyInfo.css
  src/mypage/component/ModifyInfo.js
  src/mypage/component/MyExtraInfoContent.js
  src/mypage/component/MyMatchingInfo.js
  src/mypage/component/modal/DisconnectionModal.css
  src/mypage/component/modal/DisconnectionModal.js
  src/signUp/SignUpMain.css
  src/signUp/component/QuickLoginSetup.js
  src/welfare/component/WelfareInputAddress.js
  src/welfare/component/WelfareInputBirth.js
  src/welfare/component/WelfareInputDisease.js
  src/welfare/component/WelfareInputGender.js
  src/welfare/component/WelfareInputHeight.js
  src/welfare/css/WelfareCheckPW.module.css
  src/welfare/css/WelfareInputAddress.module.css
  src/welfare/css/WelfareInputBirth.module.css
  src/welfare/css/WelfareInputDisease.module.css
  src/welfare/css/WelfareInputGender.module.css
  src/welfare/css/WelfareInputHeight.module.css
  src/welfare/css/WelfarePay.css
  src/welfare/css/WelfareSetPW.module.css
Labels: 🐞bugfix

#160 🌟(#125) 복지 예약 정보 넘기기 버그 수정중
  .gradle/8.8/fileHashes/fileHashes.lock
  src/welfare/component/WelfareCheckPW.js
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfareHanwoolModal.js
  src/welfare/component/WelfareHouseworkModal.js
  src/welfare/component/WelfareNursingModal.js
Labels: 🐞bugfix

#162 🌟(#6 ) 회원가입 간편로그인 수정완료
  src/signUp/component/QuickLoginSetup.js
Labels: 🐞bugfix

#163 🌟(#6) 회원가입 오류 수정
  src/signUp/component/QuickLoginSetup.js
Labels: 🐞bugfix

#164 [Feat]: 똑똑이 듣는중 시각화와 정보 예약페이지 전송
  src/cardCreate/application/FamilyCardYN.js
  src/chat/VoiceChat.css
  src/chat/VoiceChat.js
  src/chat/VoiceChatMovePageModal.js
  src/chat/chatScript.js
  src/onboarding/OnboardingNew.js
Labels: 🌟feature

#165 🌟(#) 파일 추가
  .well-known/assetlinks.json
Labels: 🌏deploy

#166 🌟(#125 ) 모달 css 및 버그 수정 완료
  src/consumeReport/component/ConsumeReportInfo.js
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/css/DolbomMain.module.css
  src/welfare/css/WelfareReserveModal.module.css
Labels: 🐞bugfix

#167 🌟(#6) 로그인 에러메세지 수정
  src/consume/Consumption.css
  src/consume/component/ConsumCard.css
  src/consume/component/ConsumCard.js
  src/consume/component/ConsumFilter.css
  src/consume/component/ConsumList.css
  src/image/familyCard.svg
  src/image/personalCard.svg
  src/login/LoginBio.js
  src/login/LoginId.js
  src/login/LoginPw.js
  src/mypage/component/ModifyInfo.css
  src/signUp/component/QuickLoginSetup.js
Labels: 🐞bugfix

#168 🌟(#6) 간편로그인 설정 회워가입페이지 수정
  src/login/LoginBio.js
  src/login/LoginPw.js
  src/signUp/SignUpMain.js
  src/signUp/component/QuickLoginSetup.js
Labels: 🐞bugfix

#169 🌟(#125 ) css 수정
  src/welfare/component/DolbomMain.js
  src/welfare/component/WelfareMain.js
  src/welfare/component/WelfareNursingModal.js
  src/welfare/component/WelfareReservedItem.js
  src/welfare/css/DolbomMain.module.css
  src/welfare/css/WelfarePayCompl.module.css
  src/welfare/css/WelfareReserveModal.module.css
Labels: 🐞bugfix

#170 🌟(#6) 간편로그인 회원가입페이지 수정함
  src/signUp/component/QuickLoginSetup.js
Labels: 🐞bugfix

#171 🌟(#114 ) 버튼 디자인 수정 중
  .gradle/8.8/fileHashes/fileHashes.lock
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfareList.js
  src/welfare/css/WelfareList.module.css
Labels: 🎨design

#172 🌟(#69) 메인 페이지 이미지 수정
  src/home/MainPage.css
  src/home/MainPage.js
  src/home/component/CardBottom.css
  src/home/component/CardSection.css
  src/home/component/CardSlide.css
  src/home/component/CardSlide.js
  src/home/component/WelfareSlide.css
  src/home/component/WelfareSlide.js
  src/image/home-img02.png
  src/image/home_img01.png
  src/login/service/ApiService.js
  src/signUp/SignUpMain.js
Labels: 🎨design

#173 🌟(#157 ) 온보딩 이미지 수정
  src/image/onboarding-img.png
  src/onboarding/OnboardingNew.css
  src/onboarding/OnboardingNew.js
Labels: 🎨design

#175 🌟(#174 ) 음성인식 예약화면 버그 수정
  src/chat/VoiceChat.js
  src/chat/VoiceChatMovePageModal.js
  src/chat/chatScript.js
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfareHouseworkModal.js
  src/welfare/component/WelfareNursingModal.js
  src/welfare/component/WelfarePayCompl.js
  src/welfare/component/WelfareReservedItem.js
Labels: 🐞bugfix

#177 🌟(#176) 알림내역css 수정
  src/alarm/AlarmList.js
  src/alarm/component/AlarmHistory.css
  src/alarm/component/AlarmHistory.js
  src/alarm/component/AlarmMark.css
  src/cardCreate/application/AddressSearchComponent.css
  src/home/component/Button.css
  src/home/component/CardSlide.css
  src/home/component/Header.css
  src/home/component/WelfareSlide.css
  src/home/component/WelfareSlide.js
  src/image/icon-alarm.svg
  src/image/icon-megaphone.svg
  src/login/Login.css
  src/login/LoginId.js
  src/onboarding/OnboardingNew.css
  src/onboarding/OnboardingNew.js
  src/welfare/component/CustomPagination.js
  src/welfare/component/WelfareList.js
  src/welfare/css/CustomPagination.css
  src/welfare/css/WelfareList.module.css
Labels: 🎨design

#179 🌟(#157 ) 모달 온보딩수정
  src/matching/MatchingModal.js
  src/matching/notice/Matching.css
  src/onboarding/OnboardingNew.css
  src/onboarding/OnboardingNew.js
Labels: 🎨design

#182 🌟(#181) 마이페이지 정보수정 디자인
  src/image/welfare01.svg
  src/image/welfare02.svg
  src/image/welfare03.svg
  src/mypage/component/ModifyInfo.css
  src/welfare/component/DolbomMain.js
Labels: 🎨design

#180 🌟(#179 ) 똑똑이 수정 및 글씨위치, 모달창 수정
  src/chat/VoiceChat.css
  src/chat/VoiceChat.js
  src/chat/chatScript.js
Labels: 🐞bugfix

#183 🌟(#181 ) 마이페이지 디자인 수정
  src/home/component/CardSlide.css
  src/mypage/component/InfoInput.js
  src/mypage/component/MyExtraInfoContent.js
Labels: 🎨design

#184 🌟(#175 ) 복지 마지막 화면 버그 수정 중
  src/welfare/component/DolbomMain.js
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfareInputBirth.js
  src/welfare/css/DolbomMain.module.css
  src/welfare/css/WelfareCheckSpec.module.css
  src/welfare/css/WelfareInputGender.module.css
Labels: 🐞bugfix

#187 🌟(#186 ) favicon수정
  public/favicon.ico
  public/index.html
  src/chat/VoiceChat.js
Labels: 🌟feature, 🎨design

#188 🌟 env.js 파일 추가
  .gitignore
  public/index.html
  src/login/service/ApiService.js
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfareNursingModal.js
  store_icon.png
Labels: 🌏deploy

#191 🌟 복지 예약 버그 수정
  src/welfare/component/DolbomMain.js
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfarePay.js
  src/welfare/component/WelfarePayCompl.js
  src/welfare/css/WelfareCheckSpec.module.css
  src/welfare/css/WelfarePay.css
Labels: 🐞bugfix

#192 🌟(#184 ) 복지 예약 마지막 화면 수정
  src/welfare/component/DolbomMain.js
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfarePay.js
  src/welfare/css/WelfarePay.css
Labels: 🐞bugfix

#193 🌟(#184) 이그노어 수정
  .gitignore
Labels: 🐞bugfix

#195 돌봄 메인 디자인 수정
  .gitignore
  src/welfare/component/DolbomMain.js
  src/welfare/css/DolbomMain.module.css
Labels: 🎨design

#197 🌟(#196 ) 로고 파일 및 앱 이름 변경
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/consumeReport/component/ConsumeReportInfo.js
  src/welfare/component/WelfareCheckSpec.js
Labels: 🌟feature

#198 🌟 복지 서비스 카드 버그 수정
  .gitignore
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfarePay.js
Labels: 🐞bugfix

#200 🌟(#184 ) 생년월일 입력 창 유효성 검사 추가
  src/welfare/component/WelfareInputBirth.js
Labels: 🌟feature

#201 🌟 온보딩 버그 수정
  src/login/Login.css
  src/login/LoginId.js
  src/onboarding/OnboardingNew.js
Labels: 🐞bugfix

#203 🌟(#202 ) 모든 모달 정보 넘기기 버그 수정
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfareHanwoolModal.js
  src/welfare/component/WelfareHouseworkModal.js
  src/welfare/component/WelfareNursingModal.js
Labels: 🐞bugfix

#205 🌟(#225) 앱 이름 변경
  public/manifest.json
Labels: 🔄️refactoring

#207 🌟(#205 ) 결제화면 이름 안뜨는 버그 수정
  src/welfare/component/WelfareCheckSpec.js
Labels: 🐞bugfix
