Repository Knock-and-knock/frontend, pull requests merged in 2024-08, with the labels that each got.

#7 🌟(#5) 페이지 퍼블리싱
  jsconfig.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/image/card.png
  src/image/chatimage.png
  src/image/icon/info.png
  src/image/icon/payhistory.png
  src/image/icon/payreport.png
  src/image/icon/welfare.png
  src/image/logo.png
  src/image/payAlarm.png
  src/index.js
  src/welfare/main/Main.css
  src/welfare/main/MainA.js
  src/welfare/main/MainB.js
  src/welfare/main/component/card/CardSection.js
  src/welfare/main/component/card/CardSectionA.css
  src/welfare/main/component/card/CardSectionB.css
  src/welfare/main/component/card/CardTag.js
  src/welfare/main/component/card/CreateCard.js
  src/welfare/main/component/card/IsCardSection.js
  src/welfare/main/component/chat/ChatSection.css
  src/welfare/main/component/chat/ChatSection.js
  src/welfare/main/component/header/HeaderA.css
  src/welfare/main/component/header/HeaderA.js
  src/welfare/main/component/header/HeaderB.css
  src/welfare/main/component/header/HeaderB.js
  src/welfare/main/component/header/LogoNav.js
  src/welfare/main/component/header/ProfileA.js
  src/welfare/main/component/header/ProfileB.js
  src/welfare/main/component/payAlarm/AlarmSection.css
  src/welfare/main/component/payAlarm/AlarmSection.js
  src/welfare/main/component/serviceBtn/ButtonGroup.js
  src/welfare/main/component/serviceBtn/PayBtn.js
  src/welfare/main/component/serviceBtn/PayReportBtn.js
  src/welfare/main/component/serviceBtn/WelfareBtn.js
  src/welfare/matching/Match.css
  src/welfare/matching/Match.js
  src/welfare/matching/button/NextBtn.js
  src/welfare/matching/button/SkipBtn.js
  src/welfare/matching/button/button.css
  src/welfare/matching/button/button.js
  src/welfare/matching/header/Header.css
  src/welfare/matching/header/Header.js
  src/welfare/matching/notice/FYIInput.js
  src/welfare/matching/notice/FYINotice.js
  src/welfare/matching/notice/Notice.css
  src/welfare/matching/notice/TitleNotice.js
Labels: 🌟feature, 🎨design

#9 🌟(#5) 파일위치 변경
  src/index.js
  src/main/Main.css
  src/main/MainA.js
  src/main/MainB.js
  src/main/component/card/CardSection.js
  src/main/component/card/CardSectionA.css
  src/main/component/card/CardSectionB.css
  src/main/component/card/CardTag.js
  src/main/component/card/CreateCard.js
  src/main/component/card/IsCardSection.js
  src/main/component/chat/ChatSection.css
  src/main/component/chat/ChatSection.js
  src/main/component/header/HeaderA.css
  src/main/component/header/HeaderA.js
  src/main/component/header/HeaderB.css
  src/main/component/header/HeaderB.js
  src/main/component/header/LogoNav.js
  src/main/component/header/ProfileA.js
  src/main/component/header/ProfileB.js
  src/main/component/payAlarm/AlarmSection.css
  src/main/component/payAlarm/AlarmSection.js
  src/main/component/serviceBtn/ButtonGroup.js
  src/main/component/serviceBtn/PayBtn.js
  src/main/component/serviceBtn/PayReportBtn.js
  src/main/component/serviceBtn/WelfareBtn.js
  src/matching/Match.css
  src/matching/Match.js
  src/matching/button/NextBtn.js
  src/matching/button/SkipBtn.js
  src/matching/button/button.css
  src/matching/button/button.js
  src/matching/header/Header.css
  src/matching/header/Header.js
  src/matching/notice/FYIInput.js
  src/matching/notice/FYINotice.js
  src/matching/notice/Notice.css
  src/matching/notice/TitleNotice.js
  src/welfare/main/component/serviceBtn/ButtonGroup.js
Labels: 🔄️refactoring

#8 Donghee
  src/image/Back.png
  src/image/gohome.png
  src/image/logo.png
  src/image/welfare.png
  src/index.js
  src/welfare/component/welfareMain.js
  src/welfare/component/welfarePayComplete.js
  src/welfare/component/welfareReserved.js
  src/welfare/css/WelfareMain.css
  src/welfare/css/WelfarePayComplete.css
  src/welfare/css/WelfareReserved.css
Labels: 🌟feature, 🎨design

#10 🌟(#4) 새로운 로고 사진 추가
  src/image/logo.png
Labels: 🛠️fix

#13 🌟(#5) 매칭페이지 퍼블리싱
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/chat/VoiceChat.css
  src/chat/VoiceChat.js
  src/main/MainA.js
  src/main/MainB.js
  src/main/component/card/CardSectionA.css
  src/main/component/card/CardSectionA.js
  src/main/component/card/CardSectionB.css
  src/main/component/card/CardSectionB.js
  src/main/component/card/CardTag.js
  src/main/component/card/CardTagA.js
  src/main/component/card/CardTagB.js
  src/main/component/card/IsCardSectionA.js
  src/main/component/card/IsCardSectionB.js
  src/main/component/chat/ChatSection.css
  src/main/component/chat/ChatSection.js
  src/main/component/header/HeaderA.css
  src/main/component/header/HeaderB.css
  src/main/component/header/ProfileA.js
  src/main/component/header/ProfileB.js
  src/main/component/payAlarm/AlarmSection.css
  src/main/component/payAlarm/AlarmSection.js
  src/matching/Match.css
  src/matching/Match.js
  src/matching/button/BackBtn.js
  src/matching/button/NextBtn.js
  src/matching/button/SkipBtn.js
  src/matching/button/SubmitBtn.js
  src/matching/button/button.css
  src/matching/header/Header.css
  src/matching/header/Header.js
  src/matching/notice/FYIInput.js
  src/matching/notice/Matching.css
  src/matching/notice/Matching.js
  src/matching/notice/Notice.css
  src/matching/notice/TitleInput.js
  src/matching/notice/TitleNotice.js
Labels: 🌟feature

#15 🌟(#6 ) 회원가입 페이지 퍼블리싱 시작
  package-lock.json
  package.json
  src/App.js
  src/index.js
  src/login/Login.css
  src/login/LoginBio.js
  src/login/LoginId.js
  src/login/LoginPw.js
  src/login/component/button/LoginBtn.css
  src/login/component/button/LoginBtn.js
  src/login/component/header/LoginHeader.css
  src/login/component/header/LoginHeader.js
  src/login/component/modal/LoginOptionModal.css
  src/login/component/modal/LoginOptionModal.js
  src/signUp/InfoInput.js
  src/signUp/PinCheck.js
  src/signUp/PinSetup.js
  src/signUp/QuickLoginSetup.js
  src/signUp/Register.js
  src/signUp/RoleCheck.js
  src/signUp/SignUp.css
  src/signUp/SignUpSuccess.js
  src/signUp/VerifyCode.js
  src/signUp/component/header/SignUpHeader.css
  src/signUp/component/header/SignUpHeader.js
Labels: 🌟feature

#17 🌟(#17) 카드발급페이지 퍼블리싱
  package-lock.json
  src/App.js
  src/cardCreate/CardCreate.css
  src/cardCreate/CardCreate.js
  src/cardCreate/header/CardCreateHeader.css
  src/cardCreate/header/CardCreateHeader.js
  src/chat/VoiceChat.css
  src/chat/VoiceChat.js
  src/image/create-card-image.png
  src/image/icon/cashback.png
  src/image/icon/insurance.png
  src/image/icon/medical.png
  src/index.js
  src/main/Main.css
  src/main/component/card/CardSectionA.css
  src/main/component/card/CardSectionB.css
  src/main/component/chat/ChatSection.css
  src/main/component/chat/ChatSection.js
  src/main/component/header/HeaderA.css
  src/main/component/header/HeaderB.css
  src/main/component/header/ProfileA.js
  src/main/component/header/ProfileB.js
  src/main/component/payAlarm/AlarmSection.css
  src/main/component/payAlarm/AlarmSection.js
  src/main/component/serviceBtn/ButtonGroup.js
  src/main/component/serviceBtn/WelfareBtn.js
  src/matching/Match.js
  src/matching/button/BackBtn.js
  src/matching/button/NextBtn.js
  src/matching/button/SkipBtn.js
  src/matching/button/SubmitBtn.js
  src/matching/notice/FYIInput.js
  src/matching/notice/TitleInput.js
Labels: 🌟feature

#19 🌟(#6) 아이디로그인 페이지 수정중
  src/App.js
  src/image/icon/arrow.png
  src/image/icon/bio.png
  src/image/icon/id.png
  src/image/icon/password.png
  src/image/icon/success.png
  src/image/no.png
  src/image/yes.png
  src/login/Login.css
  src/login/LoginBio.js
  src/login/LoginId.js
  src/login/component/button/LoginBtn.css
  src/login/component/button/LoginBtn.js
  src/login/component/modal/LoginOptionModal.css
  src/login/component/modal/LoginOptionModal.js
  src/login/service/ApiService.js
  src/signUp/InfoInput.js
  src/signUp/Register.js
  src/signUp/RoleCheck.js
  src/signUp/SignUp.css
  src/signUp/SignUpMain.css
  src/signUp/SignUpMain.js
  src/signUp/SignUpSuccess.js
  src/signUp/component/InfoInput.js
  src/signUp/component/PinCheck.js
  src/signUp/component/PinSetup.js
  src/signUp/component/QuickLoginSetup.js
  src/signUp/component/Register.js
  src/signUp/component/RoleCheck.js
  src/signUp/component/SignUpSuccess.js
  src/signUp/component/VerifyCode.js
  src/signUp/component/header/SignUpHeader.js
Labels: 🔄️refactoring, 🌟feature

#20 충돌 수정
  src/App.js
  src/index.js
  src/welfare/component/DolbomMain.js
  src/welfare/component/Header.js
  src/welfare/component/WelfareCheckPW.js
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfareHeader.js
  src/welfare/component/WelfareInputAddress.js
  src/welfare/component/WelfareInputBirth.js
  src/welfare/component/WelfareInputDisease.js
  src/welfare/component/WelfareInputGender.js
  src/welfare/component/WelfareInputHeight.js
  src/welfare/component/WelfareInputPW.js
  src/welfare/component/WelfareSetPW.js
  src/welfare/css/DolbomMain.module.css
  src/welfare/css/WelfareCheckPW.module.css
  src/welfare/css/WelfareCheckSpec.module.css
  src/welfare/css/WelfareInputAddress.module.css
  src/welfare/css/WelfareInputBirth.module.css
  src/welfare/css/WelfareInputDisease.module.css
  src/welfare/css/WelfareInputGender.module.css
  src/welfare/css/WelfareInputHeight.module.css
  src/welfare/css/WelfarePayComplete.css
  src/welfare/css/WelfareSetPW.css
Labels: 🐞bugfix

#24 🌟(#16) 카드발급페이지 퍼블리싱
  package-lock.json
  src/App.js
  src/cardCreate/CardCreate.css
  src/cardCreate/CardCreate.js
  src/cardCreate/application/Agreement.js
  src/cardCreate/application/CardApp.js
  src/cardCreate/application/CardApplication.css
  src/cardCreate/application/CreditInfo.js
  src/cardCreate/application/DefaultInfo.js
  src/cardCreate/application/ExtraInfo.js
  src/cardCreate/application/FundSourceInfo.js
  src/cardCreate/header/CardCreateHeader.css
  src/cardCreate/header/CardCreateHeader.js
  src/image/Back.png
  src/image/gohome.png
  src/image/icon/agreearrow.png
  src/index.css
  src/main/component/card/CardSectionA.js
  src/main/component/card/CreateCard.js
  src/matching/Match.css
  src/matching/Match.js
  src/matching/button/BackBtn.js
  src/matching/button/NextBtn.js
  src/matching/button/button.css
  src/matching/header/Header.css
  src/matching/header/Header.js
  src/matching/notice/Notice.css
Labels: 🌟feature

#27 🌟(#26) 마이페이지 퍼블리싱
  src/App.js
  src/header/Header.js
  src/login/LoginId.js
  src/login/component/header/LoginHeader.css
  src/login/component/header/LoginHeader.js
  src/login/service/ApiService.js
  src/main/component/header/ProfileA.js
  src/main/component/header/ProfileB.js
  src/mypage/MyPage.css
  src/mypage/MyPage.js
  src/mypage/component/InfoInput.js
  src/mypage/component/ModifyInfo.css
  src/mypage/component/ModifyInfo.js
  src/mypage/component/MyBasicInfo.js
  src/mypage/component/MyExtraInfo.js
  src/mypage/component/SubstituteInput.js
  src/mypage/component/modal/DisconnectionModal.css
  src/mypage/component/modal/DisconnectionModal.js
  src/signUp/SignUpMain.css
  src/signUp/component/InfoInput.js
  src/signUp/component/QuickLoginSetup.js
  src/signUp/component/VerifyCode.js
Labels: 🌟feature, 🎨design

#28 🌟(#16) 카드발급페이지 퍼블리싱
  package-lock.json
  package.json
  src/App.js
  src/cardCreate/CardCreate.js
  src/cardCreate/application/AddAddress.js
  src/cardCreate/application/AddressSearchComponent.css
  src/cardCreate/application/AddressSearchComponent.js
  src/cardCreate/application/Agreement.js
  src/cardCreate/application/CardApplication.css
  src/cardCreate/application/CreditInfo.js
  src/cardCreate/application/DefaultInfo.js
  src/cardCreate/application/ExtraInfo.js
  src/cardCreate/application/FundSourceInfo.js
  src/cardCreate/application/SimplePW.js
  src/cardCreate/header/CardCreateHeader.css
  src/cardCreate/header/CardCreateHeader.js
  src/header/Header.js
  src/header/Header.module.css
  src/matching/Match.js
  src/matching/button/NextBtn.js
  src/matching/button/SubmitBtn.js
  src/matching/notice/FYIInput.js
  src/matching/notice/Notice.css
  src/matching/notice/TitleInput.js
Labels: 🌟feature

#29 🌟(#16) 파일분할
  src/App.js
  src/App.test.js
  src/App1.js
  src/index.js
Labels: 🔄️refactoring, 🐞bugfix

#31 🌟(#26) app 파일 분할
  src/App.test.js
  src/App3.js
Labels: 🔄️refactoring, 🐞bugfix

#33 🌟(#30) App.js 파일명 2로 변경
  src/App.test.js
  src/App2.js
  src/index.js
  src/login/LoginId.js
  src/mypage/MyPage.js
  src/mypage/component/MyExtraInfo.js
  src/welfare/component/WelfareInputAddress.js
  src/welfare/component/WelfareInputDisease.js
  src/welfare/component/WelfareInputGender.js
Labels: 🔄️refactoring

#35 🌟(#34) 프론트 공유공간 이용 다른 페이지로 정보 넘기기 완료
  src/App.test.js
  src/App1.js
  src/App2.js
  src/App3.js
  src/consumeReport/ConsumeReport.css
  src/consumeReport/component/ConsumeBarChart.js
  src/consumeReport/component/ConsumeCircleChart.js
  src/consumeReport/component/ConsumeReport.js
  src/consumeReport/component/ConsumeReportDate.js
  src/consumeReport/component/ConsumeReportInfo.js
  src/header/BlueHeader.js
  src/header/Header.js
  src/index.js
  src/login/LoginId.js
  src/main/component/serviceBtn/ButtonGroup.js
  src/mypage/MyPage.js
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfareHanwoolModal.js
  src/welfare/component/WelfareHouseworkModal.js
  src/welfare/component/WelfareInputAddress.js
  src/welfare/component/WelfareInputBirth.js
  src/welfare/component/WelfareInputDisease.js
  src/welfare/component/WelfareInputGender.js
  src/welfare/component/WelfareInputHeight.js
  src/welfare/component/WelfareList.js
  src/welfare/component/WelfareNursingModal.js
  src/welfare/component/welfareInputTotal.js
  src/welfare/css/WelfareCheckSpec.module.css
  src/welfare/css/WelfareInputAddress.module.css
  src/welfare/css/WelfareInputBirth.module.css
  src/welfare/css/WelfareInputDisease.module.css
  src/welfare/css/WelfareInputHeight.module.css
  src/welfare/css/WelfareReserveModal.module.css
Labels: 🌟feature

#39 [Feat]: 소비내역 페이지 퍼블리싱 시작
  src/App.test.js
  src/App1.js
  src/App2.js
  src/App3.js
  src/consume/Consumption.css
  src/consume/Consumption.js
  src/consume/component/ConsumFilter.js
  src/consume/component/ConsumList.js
  src/header/Header.js
  src/index.js
  src/login/Login.css
  src/login/LoginId.js
  src/login/LoginPw.js
  src/login/component/button/LoginBtn.css
  src/login/component/button/LoginBtn.js
  src/login/component/modal/LoginOptionModal.css
  src/login/service/ApiService.js
  src/mypage/MyPage.js
  src/mypage/component/InfoInput.js
  src/mypage/component/ModifyInfo.css
  src/mypage/component/ModifyInfo.js
  src/mypage/component/MyBasicInfo.js
  src/mypage/component/MyExtraInfo.js
  src/mypage/component/SubstituteInput.js
  src/mypage/component/modal/DisconnectionModal.js
  src/signUp/SignUpMain.css
  src/signUp/component/InfoInput.js
  src/signUp/component/PinCheck.js
  src/signUp/component/PinSetup.js
  src/signUp/component/QuickLoginSetup.js
  src/signUp/component/Register.js
  src/signUp/component/RoleCheck.js
  src/signUp/component/VerifyCode.js
Labels: 🌟feature, 🎨design

#40 🌟(#38) merge 오류수정
  src/App1.js
  src/App2.js
  src/mypage/MyPage.js
Labels: 🐞bugfix

#41 🌟(#34) 차트 구현 완료
  package-lock.json
  package.json
  src/App1.js
  src/App2.js
  src/consumeReport/ConsumeReport.css
  src/consumeReport/component/ConsumeBarChart.js
  src/consumeReport/component/ConsumeCircleChart.js
  src/consumeReport/component/ConsumeReport.js
  src/consumeReport/component/ConsumeReportDate.js
  src/consumeReport/component/ConsumeReportInfo.js
  src/welfare/component/DolbomMain.js
Labels: 🌟feature

#42 🌟(#36 ) 챗봇이미지 변경예시추가
  package-lock.json
  src/App2.js
  src/image/chat-char.png
  src/main/component/chat/ChatSection.js
Labels: 🌟feature

#44 🌟(#43) 알림 페이지 퍼블리싱 시작
  package-lock.json
  package.json
  src/App1.js
  src/App3.js
  src/alarm/AlarmList.css
  src/alarm/AlarmList.js
  src/alarm/component/AlarmHistory.css
  src/alarm/component/AlarmHistory.js
  src/alarm/component/AlarmMark.css
  src/alarm/component/AlarmMark.js
  src/consume/Consumption.css
  src/consume/Consumption.js
  src/consume/component/ConsumDate.css
  src/consume/component/ConsumDate.js
  src/consume/component/ConsumDetailModal.css
  src/consume/component/ConsumDetailModal.js
  src/consume/component/ConsumFilter.css
  src/consume/component/ConsumFilter.js
  src/consume/component/ConsumList.css
  src/consume/component/ConsumList.js
  src/header/Header.js
  src/login/LoginId.js
  src/login/LoginPw.js
  src/login/service/ApiService.js
  src/main/MainB.js
  src/main/component/payAlarm/AlarmSection.js
  src/main/component/serviceBtn/ButtonGroup.js
  src/main/component/serviceBtn/PayBtn.js
  src/mypage/MyPage.css
  src/mypage/MyPage.js
  src/mypage/component/ModifyInfo.js
  src/mypage/component/MyExtraInfo.js
  src/mypage/component/modal/DisconnectionModal.js
  src/signUp/component/InfoInput.js
  src/signUp/component/QuickLoginSetup.js
  src/signUp/component/Register.js
  src/signUp/component/VerifyCode.js
Labels: 🌟feature, 🎨design

#46 🌟(#45) 주소 입력 모달창으로 구현 완료
  package-lock.json
  src/App2.js
  src/cardCreate/application/AddAddress.js
  src/chat/VoiceChat.js
  src/consumeReport/ConsumeReport.css
  src/consumeReport/component/ConsumeReportInfo.js
  src/login/LoginId.js
  src/login/service/ApiService.js
  src/signUp/component/QuickLoginSetup.js
  src/signUp/component/RoleCheck.js
  src/welfare/component/DolbomMain.js
  src/welfare/component/WelfareAddressModal.js
  src/welfare/component/WelfareCheckPW.js
  src/welfare/component/WelfareHouseworkModal.js
  src/welfare/component/WelfareInputAddress.js
  src/welfare/component/WelfareInputGender.js
  src/welfare/component/WelfareNursingModal.js
  src/welfare/component/WelfareSetPW.js
  src/welfare/css/WelfareCheckPW.module.css
  src/welfare/css/WelfareInputAddress.module.css
  src/welfare/css/WelfareInputGender.module.css
Labels: 🌟feature, 🐞bugfix

#47 🌟(#26) 마이페이지 대신 정보 입력 페이지 수정
  src/App1.js
  src/login/LoginId.js
  src/login/LoginPw.js
  src/matching/Match.js
  src/matching/notice/FYIInput.js
  src/matching/notice/Matching.js
  src/matching/notice/TitleInput.js
  src/mypage/MyPage.css
  src/mypage/MyPage.js
  src/mypage/component/InfoInput.js
  src/mypage/component/ModifyInfo.js
  src/mypage/component/MyBasicInfo.js
  src/mypage/component/MyExtraInfo.js
  src/onboarding/OnboardingPage.js
Labels: 🛠️fix, 🌟feature

#48 🌟(#46) 영상촬영을 위한 가라 준비 완료
  src/cardCreate/CardCreate.js
  src/cardCreate/application/DefaultInfo.js
  src/consume/Consumption.js
  src/consume/component/ConsumDetailModal.js
  src/consume/component/ConsumFilter.js
  src/consume/component/ConsumList.js
  src/main/component/chat/ChatSection.js
  src/main/component/header/ProfileA.js
  src/main/component/header/ProfileB.js
  src/main/component/payAlarm/AlarmSection.js
  src/main/component/serviceBtn/ButtonGroup.js
  src/main/component/serviceBtn/PayReportBtn.js
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfareReservedList.js
  src/welfare/component/welfarePayComplete.js
  src/welfare/css/WelfareCheckSpec.module.css
Labels: 🔄️refactoring

#50 🌟(#36 ) 음성채팅연결
  package-lock.json
  src/App2.js
  src/cardCreate/application/AddAddress.js
  src/cardCreate/application/FamilyExtraInfo.js
  src/chat/Header.module.css
  src/chat/VoiceChat.css
  src/chat/VoiceChat.js
  src/chat/VoiceHeader.js
  src/image/chat-char.png
Labels: 🔄️refactoring

#51 🌟(#26) 영상작업 되돌리기
  src/App3.js
  src/login/LoginId.js
  src/matching/Match.js
  src/mypage/MyPage.css
  src/mypage/MyPageTest.js
  src/mypage/component/InfoInput.js
  src/mypage/component/MyExtraInfo.js
  src/mypage/component/MyExtraInfoContent.js
  src/mypage/component/MyExtraInfoTest.js
Labels: 🔄️refactoring

#53 🌟(#52 ) 클론하고 파일 추가
  src/App2.js
  src/welfare/component/WelfareGoPageModal.js
  src/welfare/component/WelfareGoPayModal.js
Labels: 🔄️refactoring

#54 🌟(#36 ) 말동무 로딩/음성채팅 시 화면 시각화
  src/App2.js
  src/chat/Loading.css
  src/chat/Loading.js
  src/chat/SpeakLoading.js
  src/chat/VoiceChat.css
  src/chat/VoiceChat.js
Labels: 🌟feature

#55 🌟(#38) 소비내역 페이지 리디자인
  src/App3.js
  src/consume/Consumption.js
  src/consume/component/ConsumCard.css
  src/consume/component/ConsumCard.js
  src/consume/component/ConsumDate.css
  src/consume/component/ConsumDate.js
  src/consume/component/ConsumFilter.css
  src/consume/component/ConsumFilter.js
  src/consume/component/ConsumList.css
  src/consume/component/ConsumList.js
  src/image/card2.png
  src/login/LoginId.js
  src/main/component/header/ProfileA.js
  src/main/component/header/ProfileB.js
  src/mypage/MyPage.js
  src/mypage/component/InfoInput.js
  src/mypage/component/ModifyInfo.css
  src/mypage/component/ModifyInfo.js
  src/mypage/component/MyExtraInfo.js
  src/mypage/component/MyMatchingInfo.js
  src/mypage/component/SubstituteInput.js
  src/mypage/component/modal/DisconnectionModal.js
Labels: 🎨design

#58 🌟(#57) 소비리포트 프론트, 백 연결 완료
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  public/.well-known/assetlinks.json
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App2.js
  src/consumeReport/component/ConsumeReport.js
  src/consumeReport/component/ConsumeReportDate.js
  src/consumeReport/component/ConsumeReportInfo.js
Labels: 🌟feature

#60 🌟(#36 ) 음성채팅 메세지출력, 모션 추가
  src/chat/VoiceChat.css
  src/chat/VoiceChat.js
  src/chat/chatScript.js
  src/index.css
Labels: 🌟feature

#61 🌟(#26) 마이페이지 슬라이드 구현
  package-lock.json
  package.json
  src/alarm/AlarmList.js
  src/alarm/component/AlarmHistory.js
  src/cardCreate/CardCreate.js
  src/cardCreate/application/CardApp.js
  src/consume/component/ConsumCard.css
  src/consume/component/ConsumCard.js
  src/consume/component/ConsumFilter.css
  src/consume/component/ConsumFilter.js
  src/consume/component/ConsumList.js
  src/header/Header.js
  src/home/MainPage.js
  src/home/component/AlarmSection.css
  src/home/component/AlarmSection.js
  src/home/component/Button.css
  src/home/component/Button.js
  src/home/component/CardBottom.css
  src/home/component/CardBottom.js
  src/home/component/CardSection.css
  src/home/component/CardSection.js
  src/home/component/CardSlide.css
  src/home/component/CardSlide.js
  src/home/component/ChatSection.js
  src/home/component/Header.css
  src/home/component/Header.js
  src/home/component/WelfareSlide.css
  src/home/component/WelfareSlide.js
  src/image/home-card.png
  src/image/icon/icon-arrow.png
  src/image/icon/icon-next.png
  src/image/icon/icon-pre.png
  src/image/slide01.png
  src/image/slide02.png
  src/image/slide03.png
Labels: 🛠️fix, 🌟feature

#62 🌟(#36) 카드발급 연결
  src/App2.js
  src/cardCreate/application/AddAddress.js
  src/cardCreate/application/CardApp.js
  src/cardCreate/application/FamilyAddAddress.js
  src/chat/VoiceChat.css
  src/chat/VoiceChat.js
  src/chat/chatScript.js
Labels: 🌟feature

#64 🌟(#63 ) 생체인증 구현, 서버 배포 후 텟 요망
  .gradle/8.8/fileHashes/fileHashes.lock
  src/login/LoginBio.js
  src/signUp/component/QuickLoginSetup.js
  src/welfare/component/DolbomMain.js
  src/welfare/component/WelfareHanwoolModal.js
  src/welfare/component/WelfareHouseworkModal.js
  src/welfare/component/WelfareNursingModal.js
  src/welfare/css/WelfareReserveModal.module.css
Labels: 🌟feature

#66 🌟(#65 ) Dockerfile, nginx.conf 추가
  Dockerfile
  nginx/nginx.conf
  src/welfare/component/WelfareInputTotal.js
  src/welfare/component/WelfareMain.js
Labels: 🌏deploy

#67 🌟(#64 ) 소비리포트 백 프론트 연결 완료
  .gradle/8.8/fileHashes/fileHashes.lock
  src/App2.js
  src/alarm/AlarmList.js
  src/alarm/component/AlarmDetailModal.css
  src/alarm/component/AlarmDetailModal.js
  src/alarm/component/AlarmHistory.js
  src/alarm/component/AlarmMark.js
  src/consumeReport/component/ConsumeReportInfo.js
  src/signUp/component/QuickLoginSetup.js
  src/welfare/component/WelfareAddressModal.js
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfareReservedList.js
Labels: 🌟feature

#70 🌟(#69) 메인 페이지 기능 수정
  src/App2.js
  src/alarm/component/AlarmHistory.js
  src/chat/VoiceHeader.js
  src/consume/Consumption.js
  src/consume/component/ConsumDateModal.js
  src/consume/component/ConsumFilter.js
  src/consume/component/ConsumList.js
  src/home/MainPage.js
  src/home/component/Button.js
  src/home/component/CardBottom.css
  src/home/component/CardBottom.js
  src/home/component/CardSection.css
  src/home/component/CardSection.js
  src/home/component/CardSlide.css
  src/home/component/CardSlide.js
  src/home/component/NCardBottom.js
  src/home/component/NCardSection.js
  src/home/component/WelfareSlide.js
  src/mypage/MyPage.js
Labels: 🛠️fix, 🌟feature

#71 🌟(#68 ) 매칭 연결
  src/home/MainPage.js
  src/matching/Match.js
  src/matching/MatchingModal.css
  src/matching/MatchingModal.js
  src/matching/notice/Matching.js
Labels: 🌟feature

#72 [Rename]: 웰페어 리네임
  src/App2.js
  src/welfare/component/WelfarePayCompl.js
  src/welfare/css/WelfarePayCompl.module.css
Labels: 🔄️refactoring

#73 🌟(#69) 메인화면 카드 슬라이드 수정
  src/home/component/CardSlide.js
  src/login/service/ApiService.js
Labels: 🛠️fix

#75 🌟(#71 ) 소비내역 모달 구현
  .gradle/8.8/fileHashes/fileHashes.lock
  package-lock.json
  package.json
  src/consume/Consumption.js
  src/consume/component/ConsumDateModal.css
  src/consume/component/ConsumDateModal.js
  src/consume/component/ConsumFilter.js
  src/consumeReport/ConsumeReport.css
  src/consumeReport/component/ConsumeReportInfo.js
  src/header/Header.module.css
  src/login/service/ApiService.js
  src/signUp/SignUpMain.css
  src/signUp/component/QuickLoginSetup.js
  src/signUp/component/Register.js
  src/signUp/component/header/SignUpHeader.css
  src/welfare/component/DolbomMain.js
  src/welfare/css/DolbomMain.module.css
  src/welfare/css/WelfareReserveCancelModal.module.css
Labels: 🌟feature

#74 🌟(#65 ) workflows 추가
  .github/workflows/deploy.yml
Labels: 🌏deploy

#80 🌟(#78 ) 생체인증 구현중
  src/login/LoginBio.js
  src/signUp/component/QuickLoginSetup.js
  src/welfare/component/WelfareReservedList.js
Labels: 🌟feature

#79 🌟(#38) 소비내역 연결 중
  .gitignore
  src/alarm/component/AlarmHistory.js
  src/alarm/component/AlarmMark.js
  src/consume/Consumption.js
  src/consume/component/ConsumDateModal.js
  src/home/component/CardBottom.js
  src/home/component/CardSection.js
  src/home/component/CardSlide.js
  src/home/component/Header.js
  src/login/service/ApiService.js
Labels: 🌟feature

#81 🌟(#36) 페이지 내 불필요한 코드 삭제
  src/cardCreate/application/CardAppSuccess.js
  src/home/MainPage.js
  src/matching/notice/Matching.js
Labels: 🔄️refactoring

#82 🌟(#37 ) 똑똑이 음성보이기 ui변경/카드발급 기본정보 불러오기
  .gitignore
  src/cardCreate/application/DefaultInfo.js
  src/cardCreate/application/FamilySimplePW.js
  src/cardCreate/application/SimplePW.js
  src/chat/VoiceChat.css
  src/chat/VoiceChat.js
Labels: 🌟feature

#83 🌟(#38) 소비내역 페이지 연결중
  src/consume/Consumption.js
  src/consume/component/ConsumDateModal.js
  src/consume/component/ConsumFilter.js
  src/consume/component/ConsumList.css
  src/home/component/CardBottom.js
  src/home/component/CardSection.js
  src/login/LoginPw.js
  src/welfare/component/WelfareReservedList.js
Labels: 🌟feature

#84 🌟(#82 ) input창 auto focus
  src/cardCreate/application/SimplePW.js
Labels: 🌟feature

#86 🌟(#84 ) 복지 예약 삭제코드(테스트미완)
  .gitignore
  src/cardCreate/application/CardApplication.css
  src/chat/VoiceChat.js
  src/chat/VoiceChatMovePageModal.js
  src/chat/VoiceChatMovePayModal.js
  src/chat/chatScript.js
  src/welfare/component/WelfareReserveCancelModal.js
  src/welfare/component/WelfareReservedList.js
Labels: 🌟feature

#87 🌟(#) 생체인증 테스트 요망
  .gradle/8.8/fileHashes/fileHashes.lock
  src/consumeReport/component/ConsumeReportInfo.js
  src/mypage/MyPage.js
  src/welfare/component/WelfareInputBirth.js
  src/welfare/css/WelfareInputAddress.module.css
  src/welfare/css/WelfareInputBirth.module.css
  src/welfare/css/WelfareInputDisease.module.css
  src/welfare/css/WelfareInputGender.module.css
  src/welfare/css/WelfareInputHeight.module.css
Labels: 🌟feature

#88 🌟(#43) 이상기후알람 백연결
  src/alarm/AlarmList.js
  src/alarm/component/AlarmDetailModal.js
  src/alarm/component/AlarmHistory.js
  src/alarm/component/AlarmMark.css
  src/alarm/component/AlarmMark.js
  src/consume/Consumption.js
  src/consume/component/ConsumCard.js
  src/consume/component/ConsumDateModal.js
  src/consume/component/ConsumFilter.js
  src/consume/component/ConsumList.js
  src/home/component/Button.js
Labels: 🌟feature

#90 복지서비스 마지막 확인페이지 완성
  src/login/LoginBio.js
  src/mypage/MyPage.js
  src/welfare/component/WelfareCheckSpec.js
  src/welfare/component/WelfareHanwoolModal.js
  src/welfare/component/WelfareHouseworkModal.js
  src/welfare/component/WelfareNursingModal.js
  src/welfare/css/WelfareCheckSpec.module.css
Labels: 🌟feature

#93 [Bugfix]: 복지예약 리스트 수정중
  src/welfare/component/WelfareReservedList.js
Labels: 🐞bugfix

#91 🌟(#36) 똑똑이 모달창연결 및 인사말 로딩
  src/cardCreate/application/CardApplication.css
  src/cardCreate/application/DefaultInfo.js
  src/cardCreate/application/ExtraInfo.js
  src/cardCreate/application/FamilyAddAddress.js
  src/cardCreate/application/FamilyExtraInfo.js
  src/chat/VoiceChat.js
  src/chat/VoiceChatMovePageModal.js
  src/chat/VoiceChatMovePayModal.js
  src/chat/chatScript.js
  src/home/MainPage.js
  src/home/component/Button.js
  src/matching/Match.js
  src/matching/MatchingModal.css
  src/matching/MatchingModal.js
  src/matching/notice/Matching.css
  src/matching/notice/Matching.js
Labels: 🔄️refactoring, 🌟feature
